name: 🚀 Feature Request
description: Suggest an improvement or new capability
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What problem does this solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: Explain how you would like it to work.

