import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const organizationsDir = path.join(root, "new-api-details", "organizations");
const outputPath = path.join(root, "lib", "generated", "organization-imports.ts");
const excluded = new Set(["index.json", "metadata.json"]);
const files = fs.readdirSync(organizationsDir)
  .filter((file) => file.endsWith(".json") && !excluded.has(file))
  .sort();

const entries = files.map((file) => {
  const slug = file.slice(0, -5);
  return `  ${JSON.stringify(slug)}: () => import(${JSON.stringify(`../../new-api-details/organizations/${file}`)}),`;
});

const source = `// Generated by scripts/generate-organization-imports.ts. Do not edit manually.
export const organizationLoaders: Record<string, () => Promise<{ default: unknown }>> = {
${entries.join("\n")}
};
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, source);
console.log(`Generated ${files.length} organization import loaders.`);
